#!/usr/bin/env bash
# Two jobs, and the second one is what makes this a sandbox rather than just another
# stack:
#
#   1. INGRESS -- restrict this stack's published ports to the sources meant to reach
#      them, exactly as the other three stacks do.
#   2. EGRESS  -- stop a lab workload from reaching the rest of the LAN. Everything
#      here is disposable and frequently untrusted; the other stacks are not.
#
# Idempotent: safe to re-run (e.g. on every boot). See firewall/README.md.
set -euo pipefail

LAN_SUBNET="192.168.1.0/24"
VPN_SUBNET="10.8.0.0/24"

# Must match the ipam subnet of the lab-stack bridge in compose.yml. This is how the
# egress rules recognise "traffic from a lab workload" -- the bridge interface name is
# generated by Docker and changes, the subnet is pinned and does not.
LAB_SUBNET="172.22.0.0/16"

# Peer addresses live in .env alongside the Compose config, so the rules and the
# containers can never disagree. Read with sed rather than by sourcing -- .env holds
# secrets whose values the shell would mangle.
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"
from_env() {
  # from_env VAR_NAME DEFAULT -- an already-exported value wins, then .env, then the
  # default, so a one-off run can override without editing anything.
  local name=$1 default=$2 value="${!1:-}"
  if [ -z "$value" ] && [ -f "$ENV_FILE" ]; then
    value="$(sed -n "s/^${name}=//p" "$ENV_FILE" | head -1)"
  fi
  printf '%s' "${value:-$default}"
}

NETWORK_HOST="$(from_env NETWORK_HOST 192.168.1.39)"
MONITORING_HOST="$(from_env MONITORING_HOST 192.168.1.70)"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

docker_user_allow() {
  local proto=$1 port=$2 src=$3
  iptables -C DOCKER-USER -i eth0 -p "$proto" --dport "$port" -s "$src" -j RETURN 2>/dev/null \
    || iptables -I DOCKER-USER -i eth0 -p "$proto" --dport "$port" -s "$src" -j RETURN
}

docker_user_drop() {
  local proto=$1 port=$2
  # -i eth0 scopes this to packets actually arriving from outside the box. Traffic
  # between containers on a Docker bridge also traverses DOCKER-USER (Docker enables
  # bridge-netfilter), and a rule without -i eth0 would drop that too -- this bit
  # network-stack live during its own firewall rollout.
  iptables -C DOCKER-USER -i eth0 -p "$proto" --dport "$port" -j DROP 2>/dev/null \
    || iptables -A DOCKER-USER -i eth0 -p "$proto" --dport "$port" -j DROP
}

# ---------------------------------------------------------------------------
# 1. Ingress
# ---------------------------------------------------------------------------

# Workload ports and the docs server: LAN/VPN-wide. A workload is expected to carry its
# own login (see workloads/README.md) -- this is a network boundary, not an auth one.
# Add a line here for each workload port you publish in compose.yml.
DOCKER_PORTS=(
  "tcp:8092"   # docs-server
  "tcp:8100"   # searxng
  "tcp:8101"   # snapotter
)

# Agent ports. These have no login worth the name -- node-exporter has basic auth,
# alloy has none at all -- and between them they inventory the host and expose Alloy's
# pipeline UI. Allowlisted to the monitoring host only. NEVER move one of these into
# DOCKER_PORTS.
PEER_PORTS=(
  "tcp:9100"   # node-exporter
  "tcp:12345"  # alloy
)

PEER_HOSTS=(
  "${MONITORING_HOST}"
)

for entry in "${DOCKER_PORTS[@]}"; do
  proto="${entry%%:*}"; port="${entry##*:}"
  # Allow rules must exist (and be evaluated) before the DROP for the same port,
  # so insert-at-top for allows, append for the drop.
  docker_user_allow "$proto" "$port" "$LAN_SUBNET"
  docker_user_allow "$proto" "$port" "$VPN_SUBNET"
  docker_user_drop  "$proto" "$port"
done

for entry in "${PEER_PORTS[@]}"; do
  proto="${entry%%:*}"; port="${entry##*:}"
  for peer in "${PEER_HOSTS[@]}"; do
    docker_user_allow "$proto" "$port" "$peer"
  done
  docker_user_drop "$proto" "$port"
done

# ---------------------------------------------------------------------------
# 2. Egress containment
# ---------------------------------------------------------------------------
# A lab workload has no business talking to Pi-hole's admin page, Proxmox's API, a
# NAS, or another LXC. The internet it may have -- that is most of the point of a
# playground -- but the LAN and the VPN subnet are off limits except for the few
# flows this stack genuinely needs.
#
# Ordering matters and is the reverse of the ingress rules above: the allows are
# inserted at the top of DOCKER-USER, the catch-all drop is appended, so a packet is
# tested against every exception before it is dropped.
#
# Note these match on -s "$LAB_SUBNET", so they only ever apply to this stack's
# containers. The other three stacks' rules in the same chain are untouched, and a
# workload moved out of this subnet loses the containment with it.

lab_egress_allow() {
  # lab_egress_allow <proto> <port> <dest>
  local proto=$1 port=$2 dst=$3
  iptables -C DOCKER-USER -s "$LAB_SUBNET" -d "$dst" -p "$proto" --dport "$port" -j RETURN 2>/dev/null \
    || iptables -I DOCKER-USER -s "$LAB_SUBNET" -d "$dst" -p "$proto" --dport "$port" -j RETURN
}

lab_egress_drop() {
  # lab_egress_drop <dest-subnet>
  local dst=$1
  iptables -C DOCKER-USER -s "$LAB_SUBNET" -d "$dst" -j DROP 2>/dev/null \
    || iptables -A DOCKER-USER -s "$LAB_SUBNET" -d "$dst" -j DROP
}

# Replies to connections opened from the LAN must keep flowing, or the catch-all below
# would break every workload the moment someone browsed to it. This is the one rule
# whose absence looks like "the workload is down" rather than "egress is blocked".
iptables -C DOCKER-USER -s "$LAB_SUBNET" -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN 2>/dev/null \
  || iptables -I DOCKER-USER -s "$LAB_SUBNET" -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN

# DNS to Pi-hole. Usually unnecessary -- Docker's embedded resolver forwards on the
# container's behalf, so the query leaves as host traffic -- but a workload that sets
# its own resolver, or digs directly, would otherwise fail in a confusing way.
lab_egress_allow udp 53   "${NETWORK_HOST}"
lab_egress_allow tcp 53   "${NETWORK_HOST}"

# Alloy shipping this host's logs to Loki. Without this the stack is invisible.
lab_egress_allow tcp 3100 "${MONITORING_HOST}"

# Everything else into the LAN and the VPN: dropped.
lab_egress_drop "$LAN_SUBNET"
lab_egress_drop "$VPN_SUBNET"

# ---------------------------------------------------------------------------
# IPv6
# ---------------------------------------------------------------------------
# Same reasoning as the other stacks: eth0 has no globally-routable IPv6 today, so none
# of this is reachable. It exists so that if the router ever starts advertising IPv6
# and this host picks up a global address, these ports fail closed instead of silently
# becoming internet-reachable. There is no LAN/VPN IPv6 prefix to allowlist, so this
# blanket-drops rather than allow-then-drop.
ip6tables_user_drop() {
  local proto=$1 port=$2
  ip6tables -C DOCKER-USER -i eth0 -p "$proto" --dport "$port" -j DROP 2>/dev/null \
    || ip6tables -A DOCKER-USER -i eth0 -p "$proto" --dport "$port" -j DROP
}

for entry in "${DOCKER_PORTS[@]}" "${PEER_PORTS[@]}"; do
  proto="${entry%%:*}"; port="${entry##*:}"
  ip6tables_user_drop "$proto" "$port"
done
